### PR TITLE
docs(linux): Update 10.1 Issue Tracker Details

### PR DESCRIPTION
**Pull request by praneethbajjuri**
Issue Tracker Update containing details of
Bugs Resolved and Bugs Open.

### CODE REVIEW

**Comment by praneethbajjuri** [comment]
This PR is incomplete. Will send additional platforms and additional sections as well

**Comment by StaticRocket** [comment]
You can open the PR (or change it's type) to a draft. This will tag it differently to show that this is still in progress and will send a secondary notification when it's moved from draft to ready.

**Review by uditkumarti — APPROVED** [review]

**Review by AashvijShenai — APPROVED** [review]

**Review by jeevantelukula — APPROVED** [review]

**Comment by cshilwant** [comment]
Waiting for an ACK from SQA

**Review by n-moorthy-karunanithi — APPROVED** [review]
Reviewed.

**Pull request merged**
