### PR TITLE
source: devices: J7_family: Update performance numbers for CPSW

### PR DESCRIPTION
**Pull request by chintan013**
Update performance numbers for CPSW for J7 Devices.

### CODE REVIEW

**Review by cshilwant — APPROVED** [review]
rst syntax looks fine, will let @uditkumarti / @aniket-l to verify the performance numbers captured & integrate the PR

**Review by StaticRocket — APPROVED** [review]

**Review by uditkumarti — COMMENTED** [review]
Why CI/CD test failed to capture these numbers ?

**Comment by chintan013** [comment]
> Why CI/CD test failed to capture these numbers ?

There may be hardware issue in test farm, I will triage it.

**Comment by uditkumarti** [comment]
> > Why CI/CD test failed to capture these numbers ?
> 
> There may be hardware issue in test farm, I will triage it.

Please raise Jira for the same.

**Review by uditkumarti — APPROVED** [review]

**Pull request merged**
