### PR TITLE
style(conf): enable sphinx-copybutton

### PR DESCRIPTION
**Pull request by cshilwant**
Add sphinx-copybutton, a small sphinx extension to add a "copy" button to code blocks.

Fixes https://github.com/TexasInstruments/processor-sdk-doc/issues/25

### CODE REVIEW

**Comment by cshilwant** [comment]
@StaticRocket I see the `docker.yml` will get triggered once we integrate a patch but what if a requirement added by developer in requirements.txt doesn't exist or a typo that get's missed out?

Should there be a workflow to just build the docker image if there's a change in `requirements.txt` or `docker/*` ?

**Comment by cshilwant** [comment]
image

Sample preview with this commit

**Comment by StaticRocket** [comment]
> @StaticRocket I see the `docker.yml` will get triggered once we integrate this PR but what if a requirement added by developer in requirements.txt doesn't exist or a typo that get's missed out?
> 
> Should there be a workflow to just build the docker image if there's a change in `requirements.txt` or `docker/*` ?

I mean, I can add one pretty quickly if we really want to check *everything* automatically.

**Comment by StaticRocket** [comment]
Nitpick: Extension ordering should prioritize native extensions before listing externals.

**Comment by cshilwant** [comment]
> Nitpick: Extension ordering should prioritize native extensions before listing externals.

@StaticRocket Updated the PR!

**Review by StaticRocket — APPROVED** [review]

**Review by praneethbajjuri — APPROVED** [review]

**Pull request merged**
