### PR TITLE
Enable Dark Mode using sphinx-rtd-dark-mode

### PR DESCRIPTION
**Pull request by cshilwant**
This Sphinx extension adds a toggleable dark mode with a little icon in the bottom right hand corner which allows the user to switch between light or dark mode.

### CODE REVIEW

**Comment by cshilwant** [comment]
### Dark mode Preview

image


### Light mode Preview
image

**Comment by StaticRocket** [comment]
Is there any way to switch the logo out when in dark mode?

**Comment by cshilwant** [comment]
@StaticRocket By deafult, only text toggles between black and white.
Let me see if something can be done to the logo as well.

One option which is available is toggling between different logo in light & dark theme

**Comment by cshilwant** [comment]
Apparently lvgl docs as well facing the same in dark mode due to black text in logo - https://docs.lvgl.io/master/

**Comment by StaticRocket** [comment]
This will be an issue for any PNG images throughout the docs as well...

**Pull request closed without merging**
