### PR TITLE
fix: General cleanup

### PR DESCRIPTION
**Pull request by cshilwant**
```shell
fix(system): Drop User Guide for Servo Drive Demo

This Demo is no longer maintained & included in any of the toc tree.
Hence, purge the user guide along with associated images

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>
``` 

```shell
fix: Switch from relative links to :ref: for cross-referencing

Use :ref: for cross-referencing to arbitrary locations in the entire document

Signed-off-by: Chirag Shilwant <c-shilwant@ti.com>
```

### CODE REVIEW

**Comment by cshilwant** [comment]
Documentation preview at - https://cshilwant.github.io/processor-sdk-doc/

**Comment by cshilwant** [comment]
Baby steps to unblock - https://github.com/TexasInstruments/processor-sdk-doc/issues/16

**Comment by cshilwant** [comment]
> New warnings found with rstcheck:
> 
> ```
> source/devices/AM62X/linux/Release_Specific_Migration_Guide.rst:49: (SEVERE/4) Problems with "include" directive path:
> ```

@StaticRocket This seems to be a mask-able warning - https://github.com/sphinx-doc/sphinx/issues/11755?

**Review by jeevantelukula — APPROVED** [review]

**Review by jsuhaas22 — APPROVED** [review]

**Comment by StaticRocket** [comment]
> > New warnings found with rstcheck:
> > ```
> > source/devices/AM62X/linux/Release_Specific_Migration_Guide.rst:49: (SEVERE/4) Problems with "include" directive path:
> > ```
> 
> @StaticRocket This seems to be a maskable warning - [sphinx-doc/sphinx#11755](https://github.com/sphinx-doc/sphinx/issues/11755)?

Eh, kind of. That issue is more about providing valid absolute paths to break out of the project SOURCEDIR. Our absolute paths are supposed to be relative to the SOURCEDIR so multilevel includes and other odd things behave correctly. I think it's safe to ignore these rstcheck errors for now so long as we can verify that the path is valid. I may have a look around what's causing that if I get bored.

**Review by StaticRocket — APPROVED** [review]

**Pull request merged**
