### PR TITLE
Feature/cicd builds

### PR DESCRIPTION
**Pull request by StaticRocket**
Automatic builds and deployment to GitHub pages for any updates to the master branch.  

Use a matrix to parallelize building the docs for listed DEVFAMILY and
OS combinations. Aggregate the results to build an expected pages
artifact. Deploy the monolithic artifact to GitHub pages.

If any platform fails for any reason, the arguments and logs for that
build will be logged under a separate section of this workflow, and the
results should not be deployed.

---

Fair warning, I have tested the build and aggregation step, but I am not currently able to test the deployment step as my master branch is still locked up in the codeowners draft. I'd appreciate someone taking a look at this on their fork.

### CODE REVIEW

**Review by praneethbajjuri — DISMISSED** [review]

**Comment by StaticRocket** [comment]
Required for #41

**Comment by cshilwant** [comment]
> Fair warning, I have tested the build and aggregation step, but I am not currently able to test the deployment step as my master branch is still locked up in the codeowners draft. I'd appreciate someone taking a look at this on their fork.


@jeevantelukula Can you help in validating it on your personal fork once

**Comment by cshilwant** [comment]
@aniket-l for reviews

**Comment by jeevantelukula** [comment]
> > Fair warning, I have tested the build and aggregation step, but I am not currently able to test the deployment step as my master branch is still locked up in the codeowners draft. I'd appreciate someone taking a look at this on their fork.
> 
> @jeevantelukula Can you help in validating it on your personal fork once

build workflow works fine. For deploy workflow, there is issue with GITHUB_TOKEN permissions. I would suggest to add permissions block in deploy.yml

**Comment by jeevantelukula** [comment]
After build.yml executed github-pages artifacts are generated. When deploy.yml executes, it is unable to find the github-pages artifacts in the workflow. 
Logs: http://serenity.dal.design.ti.com:7777/ogudeviwib.sql

**Comment by cshilwant** [comment]
> @StaticRocket After build.yml executed github-pages artifacts are generated. When deploy.yml executes, it is unable to find the github-pages artifacts in the workflow. Logs: https://gist.githubusercontent.com/jeevantelukula/63a834cd32a419b479256f1dfbf6a661/raw/a016222c467b94e05d920270903474339a183983/gistfile1.txt

@StaticRocket Can you checkout

**Review by praneethbajjuri — APPROVED** [review]

**Comment by cshilwant** [comment]
@jeevantelukula Can you re-review

**Comment by StaticRocket** [comment]
Example deployment here: https://staticrocket.github.io/processor-sdk-doc/

**Review by jeevantelukula — APPROVED** [review]
LGTM

**Review by cshilwant — APPROVED** [review]

**Review by jsuhaas22 — APPROVED** [review]

**Pull request merged**
