### PR TITLE
Feature/no config

### PR DESCRIPTION
**Pull request by StaticRocket**
Take a useful chunk out of my rewrite of the config system since that was never approved in it's complete form.

This eliminates the need for the config step.

### CODE REVIEW

**Comment by nmenon** [comment]
+1

**Comment by cshilwant** [comment]
@aniket-l FYI

**Review by praneethbajjuri — DISMISSED** [review]

**Comment by StaticRocket** [comment]
Just realized that README tells people to build RTOS for J721E, which is completely broken right now. Guess I need to change that to AM57.

**Review by cshilwant — DISMISSED** [review]
Resolve merge conflicts!

**Comment by StaticRocket** [comment]
This is now blocking progress on #20

**Comment by cshilwant** [comment]
> This is now blocking progress on #20

Agreed, but this would need a +1 from @uditkumarti @aniket-l @ravi-rahul since it updates the documentation build command & will affect their documentation building & syncing bots once they pull this changes in their fork.

I'm reviewing these changes, give me a day or two to review & get back

**Comment by aniket-l** [comment]
@praneethbajjuri @StaticRocket @cshilwant 
The changes look good. I don't have a problem with this change in build command.
LGTM

cc: @ravi-rahul

**Review by aniket-l — APPROVED** [review]

**Review by praneethbajjuri — APPROVED** [review]

**Pull request merged**
